Algoritmo "VogalConsoante"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/8/2024
Var
// Seção de Declarações das variáveis 
letra: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite uma letra: ")
leia(letra)

se (letra = "A") ou (letra = "E") ou (letra = "I") ou (letra = "O") ou (letra = "U") entao
escreva("Vogal")
senao
escreva("Consoante")
fimse


Fimalgoritmo